### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by adecrepitcabbage** [emipa606/ArgoniansofBlackmarsh#1]
I appreciated your explanation of why you wouldn't be making Biotech versions of your mods.   
For those who cannot afford Biotech, or individuals like myself who  feel like HAR is a far superior way to work mods, allowing for more flexibility, some aspects of Biotech are disappointing. Wanted to avoid making it me grousing, but...

Just writing an issue here thanking you for all the incredible work you do. Maintaining mods is a pain in the hindquarters.  
Cheers to you and yours, feel free to close this one.

**Comment by emipa606** [comment]
Glad to hear it, you are most welcome!
